#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the current directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get the project root directory (the parent of webview)
const projectRoot = path.resolve(__dirname, '../..');
const pluginXmlPath = path.join(projectRoot, 'src/main/resources/META-INF/plugin.xml');
const pluginXml = fs.readFileSync(pluginXmlPath, 'utf8');
const versionMatch = pluginXml.match(/<version>\s*([^<]+)\s*<\/version>/);
if (!versionMatch) {
  console.error('Error: Could not find version in plugin.xml');
  process.exit(1);
}

const version = versionMatch[1];
console.log(`Found version: ${version}`);

// Create the version file for the webview
const versionDir = path.join(__dirname, '../src/version');
if (!fs.existsSync(versionDir)) {
  fs.mkdirSync(versionDir, { recursive: true });
}

const versionFilePath = path.join(versionDir, 'version.ts');
const versionFileContent = `// Auto-generated version file
// This file is automatically generated during the build process
// Do not edit manually

export const APP_VERSION = '${version}';
`;

fs.writeFileSync(versionFilePath, versionFileContent);
console.log(`Version file created at: ${versionFilePath}`);
